// src/lib/images.ts
import { HikingImage } from "@/types";

export const hikingImages: HikingImage[] = [
  {
    id: "1",
    title: "Yosemite Falls",
    description: "Early morning mist rising from the iconic Yosemite Falls.",
    location: "Yosemite National Park, CA",
    date: "2024-05-15",
    tags: ["waterfall", "sunrise", "national-park", "landscape"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 156,
    downloads: 89,
    author: {
      username: "nature_lover",
    },
    resolution: "4K",
  },
  {
    id: "2",
    title: "Patagonia Storm",
    description: "Dramatic clouds over Fitz Roy during a passing storm.",
    location: "Los Glaciares National Park, Argentina",
    date: "2024-03-22",
    tags: ["mountain", "patagonia", "storm", "adventure"],
    thumb: "/images/thumb/hike.jpg",
    full: "/images/thumb/hike.jpg",
    likes: 203,
    downloads: 124,
    author: {
      username: "adventure_seeker",
    },
    resolution: "4K",
  },
  {
    id: "3",
    title: "Alps Sunrise",
    description: "Golden light painting the Matterhorn at dawn.",
    location: "Zermatt, Switzerland",
    date: "2024-07-10",
    tags: ["alps", "sunrise", "switzerland", "mountains"],
    thumb: "/images/thumb/boots.jpg",
    full: "/images/thumb/boots.jpg",
    likes: 178,
    downloads: 95,
    author: {
      username: "mountain_explorer",
    },
    resolution: "4K",
  },
  {
    id: "4",
    title: "Rocky Ridge",
    description: "Rugged ridgeline trail in the Rocky Mountains.",
    location: "Rocky Mountain National Park, CO",
    date: "2024-06-18",
    tags: ["ridge", "rockies", "trail", "mountains"],
    thumb: "/images/thumb/mountain.jpg",
    full: "/images/thumb/mountain.jpg",
    likes: 142,
    downloads: 78,
    author: {
      username: "hiking_enthusiast",
    },
    resolution: "4K",
  },
  {
    id: "5",
    title: "Glacier Lake",
    description: "Turquoise waters of Moraine Lake at sunrise.",
    location: "Banff National Park, Canada",
    date: "2024-08-05",
    tags: ["lake", "glacier", "canada", "landscape", "water"],
    thumb: "/images/thumb/mountaineering.jpg",
    full: "/images/thumb/mountaineering.jpg",
    likes: 267,
    downloads: 156,
    author: {
      username: "canada_explorer",
    },
    resolution: "4K",
  },
  {
    id: "6",
    title: "Desert Dunes",
    description: "Endless golden dunes under a clear Namibian sky.",
    location: "Sossusvlei, Namibia",
    date: "2024-04-12",
    tags: ["desert", "dunes", "namibia", "landscape"],
    thumb: "/images/thumb/mountains2.jpg",
    full: "/images/thumb/mountains2.jpg",
    likes: 189,
    downloads: 102,
    author: {
      username: "desert_wanderer",
    },
    resolution: "4K",
  },
  {
    id: "7",
    title: "Forest Path",
    description: "Moss-covered path through ancient Japanese cedar forest.",
    location: "Yakushima, Japan",
    date: "2024-09-22",
    tags: ["forest", "japan", "moss", "trees"],
    thumb: "/images/thumb/pamir.webp",
    full: "/images/thumb/pamir.webp",
    likes: 234,
    downloads: 134,
    author: {
      username: "forest_whisperer",
    },
    resolution: "4K",
  },
  {
    id: "8",
    title: "Mountain Lake",
    description: "Mirror-like reflection of snow-capped peaks.",
    location: "Jotunheimen National Park, Norway",
    date: "2024-07-28",
    tags: ["lake", "reflection", "norway", "mountains", "water"],
    thumb: "/images/thumb/path.jpg",
    full: "/images/thumb/path.jpg",
    likes: 198,
    downloads: 112,
    author: {
      username: "nordic_adventurer",
    },
    resolution: "4K",
  },
  {
    id: "9",
    title: "Canyon View",
    description: "Sweeping vista from the South Rim at sunset.",
    location: "Grand Canyon, AZ",
    date: "2024-10-15",
    tags: ["canyon", "sunset", "arizona", "landscape"],
    thumb: "/images/thumb/water.jpg",
    full: "/images/thumb/water.jpg",
    likes: 176,
    downloads: 98,
    author: {
      username: "canyon_explorer",
    },
    resolution: "4K",
  },
  {
    id: "10",
    title: "Coastal Trail",
    description: "Rugged cliffs and crashing waves along the Pacific.",
    location: "Big Sur, CA",
    date: "2024-11-08",
    tags: ["coast", "ocean", "california", "adventure"],
    thumb: "/images/thumb/children.jpg",
    full: "/images/thumb/children.jpg",
    likes: 165,
    downloads: 87,
    author: {
      username: "coastal_trekker",
    },
    resolution: "4K",
  },
  {
    id: "11",
    title: "Volcano Peak",
    description: "Steam rising from the crater of an active volcano.",
    location: "Eyjafjallajökull, Iceland",
    date: "2024-02-14",
    tags: ["volcano", "iceland", "geothermal", "adventure"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 221,
    downloads: 128,
    author: {
      username: "volcano_chaser",
    },
    resolution: "4K",
  },
  {
    id: "12",
    title: "Wildflowers",
    description: "Alpine meadow bursting with summer blooms.",
    location: "Dolomites, Italy",
    date: "2024-07-03",
    tags: ["wildflowers", "meadow", "italy", "alps", "nature"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 192,
    downloads: 105,
    author: {
      username: "flower_lover",
    },
    resolution: "4K",
  },
  {
    id: "13",
    title: "Sunset Ridge",
    description: "Fiery sunset over Mauna Kea summit.",
    location: "Hawaii Volcanoes National Park",
    date: "2024-12-20",
    tags: ["sunset", "volcano", "hawaii", "ridge"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 245,
    downloads: 142,
    author: {
      username: "sunset_chaser",
    },
    resolution: "4K",
  },
  {
    id: "14",
    title: "Misty Valley",
    description: "Highland glen shrouded in morning mist.",
    location: "Glencoe, Scotland",
    date: "2024-10-28",
    tags: ["mist", "valley", "scotland", "landscape"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 173,
    downloads: 91,
    author: {
      username: "misty_mountains",
    },
    resolution: "4K",
  },
  {
    id: "15",
    title: "Waterfall Cascade",
    description: "Powerful waterfall cascading down granite cliffs.",
    location: "Skógafoss, Iceland",
    date: "2024-06-30",
    tags: ["waterfall", "iceland", "water", "landscape"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 208,
    downloads: 118,
    author: {
      username: "waterfall_hunter",
    },
    resolution: "4K",
  },
  {
    id: "16",
    title: "Autumn Forest",
    description: "Vibrant fall colors in a New England forest.",
    location: "White Mountains, NH",
    date: "2024-10-05",
    tags: ["forest", "autumn", "new-england", "trees"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 185,
    downloads: 99,
    author: {
      username: "autumn_walker",
    },
    resolution: "4K",
  },
  {
    id: "17",
    title: "Mountain Summit",
    description: "Panoramic view from a Himalayan peak.",
    location: "Annapurna Circuit, Nepal",
    date: "2024-04-25",
    tags: ["mountain", "summit", "nepal", "himalayas", "adventure"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 278,
    downloads: 167,
    author: {
      username: "summit_seeker",
    },
    resolution: "4K",
  },
  {
    id: "18",
    title: "Coastal Sunrise",
    description: "First light breaking over rugged coastline.",
    location: "Acadia National Park, ME",
    date: "2024-08-18",
    tags: ["coast", "sunrise", "maine", "ocean"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 194,
    downloads: 107,
    author: {
      username: "dawn_photographer",
    },
    resolution: "4K",
  },
  {
    id: "19",
    title: "Alpine Lake",
    description: "Crystal clear waters surrounded by peaks.",
    location: "Lake Tahoe, CA/NV",
    date: "2024-07-15",
    tags: ["lake", "alpine", "california", "nevada", "water"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 212,
    downloads: 123,
    author: {
      username: "alpine_explorer",
    },
    resolution: "4K",
  },
  {
    id: "20",
    title: "Desert Canyon",
    description: "Deep canyon carved through red rock desert.",
    location: "Zion National Park, UT",
    date: "2024-09-10",
    tags: ["canyon", "desert", "utah", "adventure"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/thumb/adventure.webp",
    likes: 231,
    downloads: 135,
    author: {
      username: "desert_hiker",
    },
    resolution: "4K",
  },
];
