// src/lib/images.ts
import { HikingImage } from "@/types";

export const hikingImages: HikingImage[] = [
  {
    id: "1",
    title: "Yosemite Falls",
    description: "Early morning mist rising from the iconic Yosemite Falls.",
    location: "Yosemite National Park, CA",
    date: "May 2024",
    tags: ["waterfall", "sunrise", "national-park"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/full/gal-1.jpg",
  },
  {
    id: "2",
    title: "Patagonia Storm",
    description: "Dramatic clouds over Fitz Roy during a passing storm.",
    location: "Los Glaciares National Park, Argentina",
    date: "March 2024",
    tags: ["mountain", "patagonia", "storm"],
    thumb: "/images/thumb/hike.jpg",
    full: "/images/full/gal-2.jpg",
  },
  {
    id: "3",
    title: "Alps Sunrise",
    description: "Golden light painting the Matterhorn at dawn.",
    location: "Zermatt, Switzerland",
    date: "July 2024",
    tags: ["alps", "sunrise", "switzerland"],
    thumb: "/images/thumb/boots.jpg",
    full: "/images/full/gal-3.jpg",
  },
  {
    id: "4",
    title: "Rocky Ridge",
    description: "Rugged ridgeline trail in the Rocky Mountains.",
    location: "Rocky Mountain National Park, CO",
    date: "June 2024",
    tags: ["ridge", "rockies", "trail"],
    thumb: "/images/thumb/mountain.jpg",
    full: "/images/full/gal-4.jpg",
  },
  {
    id: "5",
    title: "Glacier Lake",
    description: "Turquoise waters of Moraine Lake at sunrise.",
    location: "Banff National Park, Canada",
    date: "August 2024",
    tags: ["lake", "glacier", "canada"],
    thumb: "/images/thumb/mountaineering.jpg",
    full: "/images/full/gal-5.jpg",
  },
  {
    id: "6",
    title: "Desert Dunes",
    description: "Endless golden dunes under a clear Namibian sky.",
    location: "Sossusvlei, Namibia",
    date: "April 2024",
    tags: ["desert", "dunes", "namibia"],
    thumb: "/images/thumb/mountains2.jpg",
    full: "/images/full/gal-6.jpg",
  },
  {
    id: "7",
    title: "Forest Path",
    description: "Moss-covered path through ancient Japanese cedar forest.",
    location: "Yakushima, Japan",
    date: "September 2024",
    tags: ["forest", "japan", "moss"],
    thumb: "/images/thumb/pamir.webp",
    full: "/images/full/gal-7.jpg",
  },
  {
    id: "8",
    title: "Mountain Lake",
    description: "Mirror-like reflection of snow-capped peaks.",
    location: "Jotunheimen National Park, Norway",
    date: "July 2024",
    tags: ["lake", "reflection", "norway"],
    thumb: "/images/thumb/path.jpg",
    full: "/images/full/gal-8.jpg",
  },
  {
    id: "9",
    title: "Canyon View",
    description: "Sweeping vista from the South Rim at sunset.",
    location: "Grand Canyon, AZ",
    date: "October 2024",
    tags: ["canyon", "sunset", "arizona"],
    thumb: "/images/thumb/water.jpg",
    full: "/images/full/gal-9.jpg",
  },
  {
    id: "10",
    title: "Coastal Trail",
    description: "Rugged cliffs and crashing waves along the Pacific.",
    location: "Big Sur, CA",
    date: "November 2024",
    tags: ["coast", "ocean", "california"],
    thumb: "/images/thumb/children.jpg",
    full: "/images/full/gal-10.jpg",
  },
  {
    id: "11",
    title: "Volcano Peak",
    description: "Steam rising from the crater of an active volcano.",
    location: "Eyjafjallajökull, Iceland",
    date: "February 2024",
    tags: ["volcano", "iceland", "geothermal"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/full/gal-11.jpg",
  },
  {
    id: "12",
    title: "Wildflowers",
    description: "Alpine meadow bursting with summer blooms.",
    location: "Dolomites, Italy",
    date: "July 2024",
    tags: ["wildflowers", "meadow", "italy"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/full/gal-12.jpg",
  },
  {
    id: "13",
    title: "Sunset Ridge",
    description: "Fiery sunset over Mauna Kea summit.",
    location: "Hawaii Volcanoes National Park",
    date: "December 2024",
    tags: ["sunset", "volcano", "hawaii"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/full/gal-13.jpg",
  },
  {
    id: "14",
    title: "Misty Valley",
    description: "Highland glen shrouded in morning mist.",
    location: "Glencoe, Scotland",
    date: "October 2024",
    tags: ["mist", "valley", "scotland"],
    thumb: "/images/thumb/adventure.webp",
    full: "/images/full/gal-14.jpg",
  },
];
